# Generated by Django 5.2 on 2025-10-26 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('where_to_find', '0002_user_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
