# Generated by Django 5.2 on 2025-04-23 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('where_to_find', '0003_remove_post_city_remove_user_city_post_region_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Region',
            new_name='region',
        ),
    ]
