# Generated by Django 5.2 on 2025-09-20 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('where_to_find', '0005_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='country',
            field=models.ForeignKey(default=63, on_delete=django.db.models.deletion.CASCADE, to='cities_light.country'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.region'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
